from pydantic import BaseModel, Field
from typing import List

class GameContext(BaseModel):
    """Contextual information about the game and its state."""
    target_subject: str = Field(description="Specific character, item or mechanic")
    game_origin: str = Field(description="Country or region where the game was developed (e.g., RU, CN, JP, US)")
    baseline_version: str = Field(description="The version/patch used as a comparison point")
    current_version: str = Field(description="The latest known or estimated version")

class SearchPlan(BaseModel):
    """Structured queries for different research layers."""
    official: List[str] = Field(description="Queries for patch notes and developer blogs")
    pro_statistics: List[str] = Field(description="Queries for winrates and high-level stats")
    high_tier_community: List[str] = Field(description="Queries for pro-player discussions and niche forums")

class RouterResponse(BaseModel):
    """The final plan generated by the Router Agent."""
    game_name: str = Field(description="Full name of the game")
    query_language: str = Field(description="The language used by the user")
    intent_type: str = Field(description="Category of intent (e.g., 'build', 'macro', 'technical')")
    context: GameContext
    search_plan: SearchPlan